#!/bin/zsh

ln -s ${0:a:h}/zshenv $HOME/.zshenv
ln -s ${0:a:h}/zshrc $HOME/.zshrc
ln -s ${0:a:h}/gitconfig $HOME/.gitconfig
ln -s ${0:a:h}/gitignore $HOME/.gitignore
ln -s ${0:a:h}/hgignore $HOME/.hgignore
ln -s ${0:a:h}/hgrc $HOME/.hgrc
ln -s ${0:a:h}/config_kitty_ssh.conf $HOME/.config/kitty/ssh.conf
ln -s ${0:a:h}/prettierrc $HOME/.prettierrc
